### ISSUE TITLE
matchdelete in vim takes a winID?

### ISSUE THREAD

**Issue by benknoble** [statox/FYT.vim#1]
https://github.com/statox/FYT.vim/blob/ae10bc8ca19a79fae20001d4911a30c3a6887391/autoload/FYT.vim#L23

In your blog post on this, you wrote that vim has a different implementation of `matchdelete`, but my documentation says:

```
matchdelete({id} [, {win})		       *matchdelete()* *E802* *E803*
		Deletes a match with ID {id} previously defined by |matchadd()|
		or one of the |:match| commands.  Returns 0 if successful,
		otherwise -1.  See example for |matchadd()|.  All matches can
		be deleted in one operation by |clearmatches()|.
		If {win} is specified, use the window with this number or
		window ID instead of the current window.
```

So I'm not sure I follow what you're referring to, and it looks like the same code would work with vim as well.

**Comment by statox** [comment]
Hey Ben!

Thank you for pointing that out! It turns out I was running a pretty out of date vim: They introduced the `{win}` parameter with [aff749145](https://github.com/vim/vim/commit/aff749145e23c0f20b5158d1d3a942948ed138e3) about one year ago :facepalm: 

Will correct that.
