### ISSUE TITLE
Visual-block mode

### ISSUE THREAD

**Issue by benknoble** [statox/FYT.vim#2]
Trying it out a bit, and loving it! My only complaint is that yanking in visual block mode highlights the entirety of each line except the last, no matter how much was selected. Not sure how to fix that, though--perhaps a column selector in the pattern for match?

**Comment by statox** [comment]
Hey Ben.

This is an issue I was thinking about but didn't took time to handle until now.
I just added a commit which seems to fix it: I create a match for each line in the visual block and use a pattern with column selectors as you mentioned.

My first tests seem satisfying but I'll make sure to use it for a few days before closing the issue to make sure there is not an edge case I didn't see.

**Comment by benknoble** [comment]
The commit seems to be working well. I also noticed an interesting interaction with surround.vim, in which all of the surrounded text flashes--implementation details leaking out, I suppose :) Nothing for you to do about it; just wanted to mention it.

**Comment by statox** [comment]
I'll close the issue as the fix seems to be pretty stable.

Nice catch for surround.vim, indeed it is because the plugin yanks the text to highlight so not much I can do.
