### ISSUE TITLE
A call to matchdelete does not work in neovim with two arguments

### ISSUE THREAD

**Issue by nicenemo** [statox/FYT.vim#4]
A call to matchdelete does not work in NeoVIM with two arguments.
NeoVIM's 0.4.3 version only accepts one argument.

**Comment by statox** [comment]
Thanks for pointing that out @nicenemo it was because I created the plugin with newer version which handle two arguments.

I just committed a fix. I'll wait a few days before closing the issue to make sure that I didn't create an unexpected side effect.
